# Generated by Django 5.2.4 on 2025-08-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
    ]
